"""empty message

Revision ID: 3e1f1e06cff6
Revises: 3dfffc63713
Create Date: 2018-03-25 00:21:42.355000

"""

# revision identifiers, used by Alembic.
revision = '3e1f1e06cff6'
down_revision = '3dfffc63713'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
